name: Publish npm package

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Automated releases for npm packages.
        uses: mikeal/merge-release@v4.0.7
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
